config/routes.rb
Rails.application.routes.draw do

  resources :atheletes
  resources :workout_results
  resources :score_types
  resources :measurement_types
  resources :workout_movements
  resources :movement_types
  resources :movements
  resources :workouts
  get 'athletes/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :athletes

end

app/controllers/score_types_controller.rb
class ScoreTypesController < ApplicationController
  before_action :set_score_type, only: [:show, :edit, :update, :destroy]

  # GET /score_types
  # GET /score_types.json
  def index
    @score_types = ScoreType.all
  end

  # GET /score_types/1
  # GET /score_types/1.json
  def show
  end

  # GET /score_types/new
  def new
    @score_type = ScoreType.new
  end

  # GET /score_types/1/edit
  def edit
  end

  # POST /score_types
  # POST /score_types.json
  def create
    @score_type = ScoreType.new(score_type_params)

    respond_to do |format|
      if @score_type.save
        format.html { redirect_to @score_type, notice: 'Score type was successfully created.' }
        format.json { render :show, status: :created, location: @score_type }
      else
        format.html { render :new }
        format.json { render json: @score_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /score_types/1
  # PATCH/PUT /score_types/1.json
  def update
    respond_to do |format|
      if @score_type.update(score_type_params)
        format.html { redirect_to @score_type, notice: 'Score type was successfully updated.' }
        format.json { render :show, status: :ok, location: @score_type }
      else
        format.html { render :edit }
        format.json { render json: @score_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /score_types/1
  # DELETE /score_types/1.json
  def destroy
    @score_type.destroy
    respond_to do |format|
      format.html { redirect_to score_types_url, notice: 'Score type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score_type
      @score_type = ScoreType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_type_params
      params.require(:score_type).permit(:name)
    end
end

app/helpers/score_types_helper.rb
module ScoreTypesHelper
end

app/views/score_types/_form.html.erb
<%= form_for(score_type) do |f| %>
  <% if score_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score_type.errors.count, "error") %> prohibited this score_type from being saved:</h2>

      <ul>
      <% score_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/score_types/edit.html.erb
<h1>Editing Score Type</h1>

<%= render 'form', score_type: @score_type %>

<%= link_to 'Show', @score_type %> |
<%= link_to 'Back', score_types_path %>

app/views/score_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Score Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @score_types.each do |score_type| %>
      <tr>
        <td><%= score_type.name %></td>
        <td><%= link_to 'Show', score_type %></td>
        <td><%= link_to 'Edit', edit_score_type_path(score_type) %></td>
        <td><%= link_to 'Destroy', score_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score Type', new_score_type_path %>

app/views/score_types/new.html.erb
<h1>New Score Type</h1>

<%= render 'form', score_type: @score_type %>

<%= link_to 'Back', score_types_path %>

app/views/score_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @score_type.name %>
</p>

<%= link_to 'Edit', edit_score_type_path(@score_type) %> |
<%= link_to 'Back', score_types_path %>