config/routes.rb
Rails.application.routes.draw do

  resources :atheletes
  resources :workout_results
  resources :score_types
  resources :measurement_types
  resources :workout_movements
  resources :movement_types
  resources :movements
  resources :workouts
  get 'athletes/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :athletes

end

app/models/athelete.rb
class Athelete < ApplicationRecord
end

app/controllers/atheletes_controller.rb
class AtheletesController < ApplicationController
  before_action :set_athelete, only: [:show, :edit, :update, :destroy]

  # GET /atheletes
  # GET /atheletes.json
  def index
    @atheletes = Athelete.all
  end

  # GET /atheletes/1
  # GET /atheletes/1.json
  def show
  end

  # GET /atheletes/new
  def new
    @athelete = Athelete.new
  end

  # GET /atheletes/1/edit
  def edit
  end

  # POST /atheletes
  # POST /atheletes.json
  def create
    @athelete = Athelete.new(athelete_params)

    respond_to do |format|
      if @athelete.save
        format.html { redirect_to @athelete, notice: 'Athelete was successfully created.' }
        format.json { render :show, status: :created, location: @athelete }
      else
        format.html { render :new }
        format.json { render json: @athelete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atheletes/1
  # PATCH/PUT /atheletes/1.json
  def update
    respond_to do |format|
      if @athelete.update(athelete_params)
        format.html { redirect_to @athelete, notice: 'Athelete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athelete }
      else
        format.html { render :edit }
        format.json { render json: @athelete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atheletes/1
  # DELETE /atheletes/1.json
  def destroy
    @athelete.destroy
    respond_to do |format|
      format.html { redirect_to atheletes_url, notice: 'Athelete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athelete
      @athelete = Athelete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athelete_params
      params.require(:athelete).permit(:first_name, :last_name, :age)
    end
end

app/helpers/atheletes_helper.rb
module AtheletesHelper
end

app/views/atheletes/_form.html.erb
<%= form_for(athelete) do |f| %>
  <% if athelete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(athelete.errors.count, "error") %> prohibited this athelete from being saved:</h2>

      <ul>
      <% athelete.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atheletes/edit.html.erb
<h1>Editing Athelete</h1>

<%= render 'form', athelete: @athelete %>

<%= link_to 'Show', @athelete %> |
<%= link_to 'Back', atheletes_path %>

app/views/atheletes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Atheletes</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atheletes.each do |athelete| %>
      <tr>
        <td><%= athelete.first_name %></td>
        <td><%= athelete.last_name %></td>
        <td><%= athelete.age %></td>
        <td><%= link_to 'Show', athelete %></td>
        <td><%= link_to 'Edit', edit_athelete_path(athelete) %></td>
        <td><%= link_to 'Destroy', athelete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Athelete', new_athelete_path %>

app/views/atheletes/new.html.erb
<h1>New Athelete</h1>

<%= render 'form', athelete: @athelete %>

<%= link_to 'Back', atheletes_path %>

app/views/atheletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @athelete.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @athelete.last_name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @athelete.age %>
</p>

<%= link_to 'Edit', edit_athelete_path(@athelete) %> |
<%= link_to 'Back', atheletes_path %>