config/routes.rb
Rails.application.routes.draw do

  resources :atheletes
  resources :workout_results
  resources :score_types
  resources :measurement_types
  resources :workout_movements
  resources :movement_types
  resources :movements
  resources :workouts
  get 'athletes/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :athletes

end

app/controllers/movement_types_controller.rb
class MovementTypesController < ApplicationController
  before_action :set_movement_type, only: [:show, :edit, :update, :destroy]

  # GET /movement_types
  # GET /movement_types.json
  def index
    @movement_types = MovementType.all
  end

  # GET /movement_types/1
  # GET /movement_types/1.json
  def show
  end

  # GET /movement_types/new
  def new
    @movement_type = MovementType.new
  end

  # GET /movement_types/1/edit
  def edit
  end

  # POST /movement_types
  # POST /movement_types.json
  def create
    @movement_type = MovementType.new(movement_type_params)

    respond_to do |format|
      if @movement_type.save
        format.html { redirect_to @movement_type, notice: 'Movement type was successfully created.' }
        format.json { render :show, status: :created, location: @movement_type }
      else
        format.html { render :new }
        format.json { render json: @movement_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movement_types/1
  # PATCH/PUT /movement_types/1.json
  def update
    respond_to do |format|
      if @movement_type.update(movement_type_params)
        format.html { redirect_to @movement_type, notice: 'Movement type was successfully updated.' }
        format.json { render :show, status: :ok, location: @movement_type }
      else
        format.html { render :edit }
        format.json { render json: @movement_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movement_types/1
  # DELETE /movement_types/1.json
  def destroy
    @movement_type.destroy
    respond_to do |format|
      format.html { redirect_to movement_types_url, notice: 'Movement type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement_type
      @movement_type = MovementType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_type_params
      params.require(:movement_type).permit(:name)
    end
end

app/helpers/movement_types_helper.rb
module MovementTypesHelper
end

app/views/movement_types/_form.html.erb
<%= form_for(movement_type) do |f| %>
  <% if movement_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movement_type.errors.count, "error") %> prohibited this movement_type from being saved:</h2>

      <ul>
      <% movement_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movement_types/edit.html.erb
<h1>Editing Movement Type</h1>

<%= render 'form', movement_type: @movement_type %>

<%= link_to 'Show', @movement_type %> |
<%= link_to 'Back', movement_types_path %>

app/views/movement_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movement Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movement_types.each do |movement_type| %>
      <tr>
        <td><%= movement_type.name %></td>
        <td><%= link_to 'Show', movement_type %></td>
        <td><%= link_to 'Edit', edit_movement_type_path(movement_type) %></td>
        <td><%= link_to 'Destroy', movement_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movement Type', new_movement_type_path %>

app/views/movement_types/new.html.erb
<h1>New Movement Type</h1>

<%= render 'form', movement_type: @movement_type %>

<%= link_to 'Back', movement_types_path %>

app/views/movement_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movement_type.name %>
</p>

<%= link_to 'Edit', edit_movement_type_path(@movement_type) %> |
<%= link_to 'Back', movement_types_path %>